const mongoose = require('mongoose');

/**
 * Invoice — water usage billing record generated by Office Manager
 * for a Farmer / Farm Owner. Farmer can view, pay, and upload receipts.
 */
const InvoiceSchema = new mongoose.Schema({
  farmId:       { type: mongoose.Schema.Types.ObjectId, ref: 'Farm',  required: true },
  farmOwnerId:  { type: mongoose.Schema.Types.ObjectId, ref: 'User',  required: true },
  generatedBy:  { type: mongoose.Schema.Types.ObjectId, ref: 'User',  required: true }, // office_manager
  invoiceNumber:{ type: String, required: true },   // unique enforced via schema.index() below

  /* Billing period */
  periodStart:  { type: Date, required: true },
  periodEnd:    { type: Date, required: true },

  /* Water usage */
  waterUsedLitres: { type: Number, default: 0, min: 0 },
  ratePerLitre:    { type: Number, default: 0, min: 0 }, // ETB per litre
  waterCharge:     { type: Number, default: 0, min: 0 }, // computed

  /* Extra charges */
  maintenanceFee:  { type: Number, default: 0, min: 0 },
  serviceCharge:   { type: Number, default: 0, min: 0 },
  tax:             { type: Number, default: 0, min: 0 }, // amount (not %)
  discount:        { type: Number, default: 0, min: 0 },

  totalAmount: { type: Number, default: 0, min: 0 }, // auto-computed on save

  /* Payment */
  paymentStatus: {
    type: String,
    enum: ['pending', 'partially_paid', 'paid', 'overdue', 'cancelled'],
    default: 'pending',
  },
  paidAmount:   { type: Number, default: 0, min: 0 },
  paidAt:       { type: Date },
  dueDate:      { type: Date },

  /* Receipt upload (base64 or URL string) */
  receiptImage: { type: String, default: '' },
  receiptNote:  { type: String, default: '' },

  notes: { type: String, default: '' },
}, { timestamps: true });

/* Auto-generate invoice number if not provided */
InvoiceSchema.pre('validate', async function () {
  if (!this.invoiceNumber) {
    const year  = new Date().getFullYear();
    const count = await this.constructor.countDocuments();
    this.invoiceNumber = `INV-${year}-${String(count + 1).padStart(5, '0')}`;
  }
});

/* Auto-compute totals before save */
InvoiceSchema.pre('save', function () {
  this.waterCharge = parseFloat((this.waterUsedLitres * this.ratePerLitre).toFixed(2));
  this.totalAmount = parseFloat((
    this.waterCharge + this.maintenanceFee + this.serviceCharge + this.tax - this.discount
  ).toFixed(2));

  // Auto-update status based on paid amount
  if (this.paidAmount >= this.totalAmount && this.totalAmount > 0) {
    this.paymentStatus = 'paid';
    if (!this.paidAt) this.paidAt = new Date();
  } else if (this.paidAmount > 0 && this.paidAmount < this.totalAmount) {
    this.paymentStatus = 'partially_paid';
  }
  // Mark overdue if due date passed and not paid
  if (this.dueDate && new Date() > this.dueDate && this.paymentStatus === 'pending') {
    this.paymentStatus = 'overdue';
  }
});

InvoiceSchema.index({ farmId: 1, paymentStatus: 1 });
InvoiceSchema.index({ farmOwnerId: 1 });
InvoiceSchema.index({ generatedBy: 1 });
InvoiceSchema.index({ invoiceNumber: 1 }, { unique: true });

module.exports = mongoose.model('Invoice', InvoiceSchema);
